name: Build and deploy Angular app to Azure Web App - inventory-management-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'  # Ensure this matches your Angular project requirements

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --configuration production  # Ensures a production build if needed

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: ./dist/frontend/browser/  # Ensure this matches the output path in angular.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production  # Correct syntax for environment definition
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C846EDACB21446F852A565A9D67FFA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53921AAA32BE40FBA81F0BAF098721CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D2A1B459927946FEA23D485258322FA3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inventory-management-frontend'
          slot-name: 'Production'
          package: ./dist/frontend/browser/  # Ensure this path matches your build output
